name: Build

on: [push, pull_request]
#on:
#  push:
#    branches: [ "1.20.1-community" ]
#  pull_request:
#    branches: [ "1.20.1-community" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Build with Gradle Wrapper
      run: ./gradlew --no-daemon build
    - uses: actions/upload-artifact@v4
      with:
        name: Destroy
        path: |
          build/libs/destroy-*.jar
          !build/libs/destroy-*-all.jar
          !build/libs/destroy-*-sources.jar
